import azure.functions as func
import pymongo
from bson.objectid import ObjectId                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                       
def main(req: func.HttpRequest) -> func.HttpResponse:                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                       
    id = req.params.get('id')                                                                                                                                                                                                                                                          
    request = req.get_json()                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                       
    if request:                                                                                                                                                                                                                                                                        
        try:                                                                                                                                                                                                                                                                           
            url = "mongodb://nd2hospitalcosmos:AfxPATz1CbyX6S8jSZZl7raUblTkB6OLjeWJYsXqxFAgYumFzt9AHeFpGd3GGscLoGyjdItswYA2P30xm6hA0w==@nd2hospitalcosmos.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@nd2hospitalcosmos@"
            client = pymongo.MongoClient(url)                                                                                                                                                                                                                                          
            database = client['nd2hospitaldb']                                                                                                                                                                                                                                                 
            collection = database['advertisements']                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                       
            filter_query = {'_id': str(id)}                                                                                                                                                                                                                                       
            update_query = {"$set": eval(request)}                                                                                                                                                                                                                                     
            rec_id1 = collection.update_one(filter_query, update_query)                                                                                                                                                                                                                
            return func.HttpResponse(status_code=200)                                                                                                                                                                                                                                  
        except:                                                                                                                                                                                                                                                                        
            print("could not connect to mongodb")                                                                                                                                                                                                                                      
            return func.HttpResponse('Could not connect to mongodb', status_code=500)
    else:
        return func.HttpResponse('Please pass name in the body', status_code=400)

